import {QuoteModel} from '../models/quote.model';

export const GOLDEN_TEACHING: QuoteModel[] = [
  {content: 'Szeresd Istent tiszta szívvel.'},
  {content: 'Ha etikai elvek szerint élsz, teljesíteni tudod dharmádat. Fogadd el az erkölcsi elveket, és tartsd be őket, amíg csak élsz.'},
  {content: 'Amit meg akarsz tenni, tedd szilárd elhatározással, így a siker biztosan nem marad el.'},
  {content: 'Ragaszkodj az igazsághoz, tarts ki mellette mindig. Ne gondolkodj negatívan, s tégy mindig jót.'},
  {content: 'Ne hagyd abba, amit elkezdtél. Az úton mindig támadnak akadályok, ahogy rózsa sincsen tövis nélkül. Bízz önmagadban, s távolítsd el az akadályokat, így Isten kegyelmével utad célhoz vezet.'},
  {content: 'Ne függj másoktól! Állj a saját lábadon. Bízz képességeidben, és Isten megsegít.'},
  {content: 'Cselekedeteid sikere belső meggyőződésed erejétől és önfegyelmedtől függ. Ne veszítsd el a bátorságod, és soha ne add fel.'},
  {content: 'A külső tisztaság nem elegendő. A tudat tisztaságához külső és belső tisztaságra egyaránt szükség van.'},
  {content: 'Légy igaz, ne légy képmutató. Az igazság mindig győzedelmes.'},
  {content: 'Légy jó és segítőkész mindenkor, minden teremtményhez. Ezáltal magadnak is segítesz.'},
  {content: 'Óvakodj a fölényességtől. Egyformán tisztelj mindenkit.'},
  {content: 'Amit magadénak hiszel - nem állandó. Szabadulj meg a gőgtől.'},
  {content: 'Ne légy eltelve sem gazdagságoddal, sem tudásoddal. Mindig akad nálad jobb.'},
  {content: 'Légy becsületes, azzal nem veszítesz semmit. A tisztességtelenség végül mindig elbukik.'},
  {content: 'Ne dicsérd magad. Mások dicsérhetnek, de a nagyság a szerénységben rejlik.'},
  {content: 'Ne engedd, hogy a problémák elbátortalanítsanak. A földi élet az öröm és bánat partjai között folyik. Aki elveszíti bátorságát, soha nem ér célhoz. Hittel és belső bizonyossággal teljesítsd kötelességed.'},
  {content: 'Feladatodat ne halaszd holnapra, végezd el azonnal. Jó szándékaidat váltsd valóra ma; hiszen minden pillanat megismételhetetlen.'},
  {content: 'Tarts tiszteletben mindenkit egyformán. Légy mindig kész segíteni. Ha nem cselekszünk jót és nem a helyeset tesszük, mi értelme életünknek?'},
  {content: 'Minden élvezet múló Ne engedj csábításuknak, bármily vonzónak tûnnek is. Igazi örömöt csak minden élőlény önzetlen szolgálata nyújt, ebben van a bölcsesség és az élet értelme.'},
  {content: 'Ne fecséreld el az időt! Életed minden másodperce értékes és pótolhatatlan. Az elmúlt idő nem tér vissza, az idő nem vár senkire. Aki nem tart lépést vele, lemarad, ezért jól használd ki az idődet.'},
  {content: 'Mindenkinek vannak jó és rossz szokásai. Ne mások hibáit tekintsd, fedezd fel inkább a jó tulajdonságaikat és vedd át őket. Mindenkitől tanulj valami jót.'},
  {content: 'Ne engedd, hogy rossz szokásaid alakuljanak ki, melyeket azután nehéz levetkőzni, és amelyek tönkre tehetik életedet. Ápold jó szokásaidat, ezek egész életedben segítségedre lesznek. Kerüld a mérgező szereket, a dohányt, alkoholt és kábítószert, azok csak betegséget és halált hoznak a házba.'},
  {content: 'Kelj fel napkelte előtt, és végezd el a spirituális gyakorlataidat. Jótékony hatásuk egész nap veled marad.'},
  {content: 'Légy mértékletes az evésben. Az ízek mértéktelen élvezete lustasághoz és betegséghez vezet.'},
  {content: 'Tiszteld szüleidet, tanítóidat, mesteredet. Élj szeretetben és harmóniában családoddal.'},
  {content: 'Mindig az igazsághoz tartsd magad. Életed árán is tartsd meg adott szavad.'},
  {content: 'Szavaid és tetteid összhangban legyenek.'},
  {content: 'Csak fontos dolgokat adj tovább. A sekélyes beszéd, a pletykálkodás elvesztegetett idő.'},
  {content: 'Maradj hűséges társadhoz és kerüld a hűtlenségre csábító helyzeteket.'},
  {content: 'Soha ne az első benyomás alapján hozz döntést. Várj, tájékozódj alaposabban, így elkerülheted a felesleges csalódást.'},
  {content: 'A barátok közötti pénzkölcsönzés veszélyezteti a barátságot, mert ha késik a visszafizetés, keserűség lehet a következménye. Adj nyílt szívvel, de mérlegeld előbb, mit teszel!'},
  {content: 'A szükségtelenül felhalmozott anyagi javak teherré válnak, gondot okoznak. Az anyagi jólét múlandó. Lakshmí, a bőség istenasszonya nem állja a fogságot. Vagyonunkat legjobb a segítségnyújtás és adakozás eszközének tekinteni.'},
  {content: 'Ne mondj ki olyan szót, amelyet később megbánhatsz. Ne tégy semmit elveid ellenére, se olyasmit, amivel elveszítheted önbecsülésedet, vagy az ellenségeskedés magvait hinted el.'},
  {content: 'Kerüld a felesleges vitákat, veszekedést és a rossz társaságot. Kerüld a szerencsejátékot. Jó és bölcs emberek társaságát keresd. Soha ne mondj rosszat szüleidről és mesteredről, és ne hallgass meg ilyen beszédet. Ne szerezz ellenségeket meggondolatlan cselekedetekkel. Ne panaszold folyton a gondjaidat.'},
  {content: 'Tégy meg mindent az erkölcsi eszmények megvalósulásáért. Ez hozzájárul a lét harmóniájához.'},
  {content: 'Tanulj meg uralkodni érzékeiden. Ne engedd át magad vágyaidnak, ne hagyd, hogy függésben tartsanak.'},
  {content: 'A tunyaság az ember egyik legnagyobb ellensége. Erőfeszítés nélkül nem érhetsz célt. Küzd le lustaságodat.'},
  {content: 'Ne vesztegesd életedet élvezetek hajszolására. Ne engedd, hogy szenvedélyek rabja légy. Miként a méhecske megrészegül a lótuszvirág csábos illatától, és alkonyatkor szirmait összezáró virág foglya marad, úgy pazarolható el az élet a futó érzéki élvezetek kergetésében. Légy kitartó a spirituális tudás kutatásában, és tudatod fejlesztésében.'},
  {content: 'Ne vedd semmibe a természet törvényeit. Ha a természet ellen teszel, el kell viselned következményeit.'},
  {content: 'Amikor vihar van a hullámok magasra csapnak, ne akkor merülj az igazgyöngyért a tenger mélyére.'},
  {content: 'Példát a szentekről és nagy személyiségekről végy. Amit valaki elér, csakis saját erőfeszítésének köszönheti.'},
  {content: 'Aki a legmagasabb rendű tudásról beszél anélkül, hogy megvalósította volna, az mély tudatlanságban él. Legyen bármilyen művelt, szavai nélkülözik a tökéletességet.'},
  {content: 'Hiába ölti fel valaki a szerzetesi ruhát, s fordít hátat a világi életnek; ha belülről még nem tisztult meg, és nem a helyes cselekedetek útján jár, - lemondása értelmetlen.'},
  {content: 'Kerüld azokat a helyeket, ahol nem látnak szívesen.'},
  {content: 'A vagyont becsületes úton kell megszerezni. Jövedelmedet saját munkáddal, saját erőfeszítéseddel szerezd meg, és jóra használd.'},
  {content: 'Ne csak elvenni, adni is tanulj meg. Folyton kapni súlyos teher, s csak ha adunk, tehetjük le.'},
  {content: 'Légy jó minden teremtményhez. Aki másokat bánt, önmagát bántja.'},
  {content: 'Úgy bánj másokkal, amilyen bánásmódot te is szeretnél. Mindent visszakapsz, amit adtál.'},
  {content: 'Szeress minden élőlényt legalább annyira, mint önmagadat.'},
  {content: 'Isten fénye minden élőlényben ott van. Szeretni és szolgálni őket Isten szolgálatát jelenti.'},
  {content: 'Enni, inni, aludni - ehhez minden élőlény jól ért. Az ember abban különbözik az állatoktól, hogy életének célja az önmegismerés és az önmegvalósítás.'},
  {content: 'A szeretet ébreszti fel a tökéletes önmegvalósítást.'},
  {content: 'A tudás határtalan. Merülj el benne! Az élet rövid, az idő gyorsan halad, tapasztalataink végesek. Engedd el, ami a múlté, és tudd, hogy a jelen pillanat is rögtön múlttá válik - a jelenben alakítsd jövődet.'},
  {content: 'Ezért ébredjetek, testvéreim! Ne feledkezzetek meg kötelességeitekről, és teljesítsétek dharmátokat.'}
];
